### PR TITLE
[WIP] Added the initial implementation of read_plain_boolean

### PR DESCRIPTION
**Pull request by dalazx**

### CODE REVIEW

**Comment by dalazx** [comment]
@bdrosen96 please take a look

**Comment by bdrosen96** [comment]
lgtm so far.

**Comment by dalazx** [comment]
Unfortunately don't have the contributor's rights to merge.

**Comment by bdrosen96** [comment]
you should have access now. Let me know if not

**Comment by dalazx** [comment]
thanks

**Pull request merged**
